# Generated by Django 4.2 on 2023-11-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectroStockApp', '0002_alter_box_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='budgetlog',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='budgetlog',
            name='element',
        ),
        migrations.RemoveIndex(
            model_name='log',
            name='ElectroStoc_quantit_fa40ee_idx',
        ),
        migrations.AddField(
            model_name='element',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ingrese el precio en dolares', max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='log',
            name='dateOut',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de devolucion'),
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='BudgetLog',
        ),
    ]
