# Generated by Django 4.2 on 2023-06-02 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ElectroStockApp", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="borrower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowed_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="lender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lender_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="status",
            field=models.CharField(
                choices=[
                    ("AP", "Aprobado"),
                    ("DAP", "Desaprobado"),
                    ("CAR", "Carrito"),
                    ("PED", "Pedido"),
                    ("ROT", "Descompuesto"),
                    ("COM", "Comprado"),
                ],
                default="DAP",
                max_length=30,
            ),
        ),
    ]
