# Generated by Django 4.2 on 2023-04-27 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ElectroStockApp", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="responsable",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loan",
            name="borrower",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans_borrowed",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loan",
            name="lender",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans_lent",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
