# Generated by Django 4.2 on 2023-11-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectroStockApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='budgetlog',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='log',
            name='dateIn',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['name'], name='ElectroStoc_name_113c5f_idx'),
        ),
    ]
