# Generated by Django 4.2 on 2023-05-02 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ElectroStockApp', '0002_inventory_responsable_loan_borrower_loan_lender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='año',
        ),
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ElectroStockApp.year'),
            preserve_default=False,
        ),
    ]
