# Generated by Django 4.2 on 2023-04-23 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ElectroStockApp", "0003_customuser")]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ElectroStockApp.specialty",
            ),
        )
    ]
