# Generated by Django 4.2 on 2023-05-30 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ElectroStockApp", "0003_year_remove_course_año_course_number")]

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minimumStock", models.IntegerField()),
                ("name", models.CharField(max_length=30)),
            ],
            options={"verbose_name": "", "verbose_name_plural": ""},
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AP", "Aprobado"),
                            ("DAP", "Desaprobado"),
                            ("CAR", "Carrito"),
                            ("PED", "Pedido"),
                        ],
                        default="DAP",
                        max_length=30,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("observation", models.CharField(max_length=100)),
                ("dateIn", models.DateTimeField(null=True)),
                ("dateOut", models.DateTimeField(null=True)),
            ],
            options={"verbose_name": "Prestamo", "verbose_name_plural": "Prestamos"},
        ),
        migrations.RemoveField(model_name="budget", name="specialty"),
        migrations.DeleteModel(name="BudgetDetail"),
        migrations.RemoveField(model_name="destination", name="budget"),
        migrations.RemoveField(model_name="details", name="budget"),
        migrations.RemoveField(model_name="details", name="inventory"),
        migrations.RemoveField(model_name="historyinventory", name="inventory"),
        migrations.RemoveField(model_name="historyinventory", name="location"),
        migrations.RemoveField(model_name="historyloan", name="loan"),
        migrations.RemoveField(model_name="historyloan", name="status"),
        migrations.RemoveField(model_name="inventory", name="elemento"),
        migrations.RemoveField(model_name="inventory", name="responsable"),
        migrations.RemoveField(model_name="loan", name="borrower"),
        migrations.RemoveField(model_name="loan", name="lender"),
        migrations.RemoveField(model_name="loan", name="status"),
        migrations.RemoveField(model_name="purchaselocation", name="elementos"),
        migrations.RemoveField(model_name="subcategory", name="category"),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Curso", "verbose_name_plural": "Cursos"},
        ),
        migrations.RenameField(
            model_name="element", old_name="stock", new_name="initialStock"
        ),
        migrations.RenameField(
            model_name="location", old_name="laboratory", new_name="laboratoy"
        ),
        migrations.RemoveField(model_name="course", name="specialty"),
        migrations.RemoveField(model_name="customuser", name="speciality"),
        migrations.RemoveField(model_name="element", name="subcategory"),
        migrations.RemoveField(model_name="laboratory", name="laboratory"),
        migrations.RemoveField(model_name="location", name="location"),
        migrations.AddField(
            model_name="element",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="ElectroStockApp.category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="laboratory",
            name="name",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="name",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_categories",
                to="ElectroStockApp.category",
            ),
        ),
        migrations.AlterField(
            model_name="course", name="number", field=models.IntegerField()
        ),
        migrations.AlterField(
            model_name="element",
            name="ecommerce",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="element",
            name="price_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("Electronica", "Electronica"),
                    ("Programacion", "Programacion"),
                    ("Electromecanica", "Electromecanica"),
                    ("Otro", "Otro"),
                ],
                default="Electronica",
                max_length=30,
                verbose_name="Especialidad",
            ),
        ),
        migrations.DeleteModel(name="Budget"),
        migrations.DeleteModel(name="Destination"),
        migrations.DeleteModel(name="Details"),
        migrations.DeleteModel(name="HistoryInventory"),
        migrations.DeleteModel(name="HistoryLoan"),
        migrations.DeleteModel(name="Inventory"),
        migrations.DeleteModel(name="Loan"),
        migrations.DeleteModel(name="PurchaseLocation"),
        migrations.DeleteModel(name="Specialty"),
        migrations.DeleteModel(name="Status"),
        migrations.DeleteModel(name="SubCategory"),
        migrations.DeleteModel(name="Year"),
        migrations.AddField(
            model_name="log",
            name="borrower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowed_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="box",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ElectroStockApp.box"
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="lender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lender_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="element",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ElectroStockApp.element",
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ElectroStockApp.location",
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
