# Generated by Django 4.2 on 2023-05-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ElectroStockApp",
            "0004_box_log_remove_budget_specialty_delete_budgetdetail_and_more",
        )
    ]

    operations = [
        migrations.AlterField(
            model_name="laboratory",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("Electromecanica", "Electromecanica"),
                    ("Programacion", "Programacion"),
                    ("Electronica", "Electronica"),
                    ("Otro", "Otro"),
                ],
                default="Electronica",
                max_length=30,
                verbose_name="Especialidad",
            ),
        )
    ]
