# Generated by Django 4.2 on 2023-05-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ElectroStockApp", "0005_alter_laboratory_specialty")]

    operations = [
        migrations.AlterField(
            model_name="laboratory",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("Otro", "Otro"),
                    ("Electronica", "Electronica"),
                    ("Electromecanica", "Electromecanica"),
                    ("Programacion", "Programacion"),
                ],
                default="Electronica",
                max_length=30,
                verbose_name="Especialidad",
            ),
        )
    ]
