# Generated by Django 4.2 on 2023-04-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("ElectroStockApp", "0006_customuser_delete_usuarios"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_users",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_users",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
