# Generated by Django 4.2 on 2023-05-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ElectroStockApp", "0006_alter_laboratory_specialty")]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_categories",
                to="ElectroStockApp.category",
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ElectroStockApp.category",
            ),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("Electromecanica", "Electromecanica"),
                    ("Electronica", "Electronica"),
                    ("Programacion", "Programacion"),
                    ("Otro", "Otro"),
                ],
                default="Electronica",
                max_length=30,
                verbose_name="Especialidad",
            ),
        ),
    ]
