# Generated by Django 4.2 on 2023-06-05 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ElectroStockApp", "0007_category_name_alter_category_category_and_more")
    ]

    operations = [
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Speciality", models.CharField(max_length=40)),
            ],
            options={
                "verbose_name": "Especialidad",
                "verbose_name_plural": "Especialidades",
            },
        ),
        migrations.AlterModelOptions(
            name="box", options={"verbose_name": "Box", "verbose_name_plural": "Boxes"}
        ),
        migrations.RenameField(
            model_name="course", old_name="number", new_name="grade"
        ),
        migrations.RemoveField(model_name="element", name="initialStock"),
        migrations.RemoveField(model_name="laboratory", name="specialty"),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="element",
            name="price_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ingrese el precio en dolares",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="borrower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowed_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="dateOut",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="log",
            name="lender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lender_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="observation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="log",
            name="status",
            field=models.CharField(
                choices=[
                    ("AP", "Aprobado"),
                    ("DAP", "Desaprobado"),
                    ("CAR", "Carrito"),
                    ("PED", "Pedido"),
                    ("COM", "Comprado"),
                    ("DEV", "Devuelto"),
                ],
                default="DAP",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="specialties",
            field=models.ManyToManyField(
                blank=True, null=True, to="ElectroStockApp.speciality"
            ),
        ),
        migrations.AddField(
            model_name="laboratory",
            name="specialties",
            field=models.ManyToManyField(
                blank=True, null=True, to="ElectroStockApp.speciality"
            ),
        ),
    ]
