# Generated by Django 4.2 on 2023-05-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ElectroStockApp", "0007_category_name_alter_category_category_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="initialStock",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("Electromecanica", "Electromecanica"),
                    ("Programacion", "Programacion"),
                    ("Electronica", "Electronica"),
                    ("Otro", "Otro"),
                ],
                default="Electronica",
                max_length=30,
                verbose_name="Especialidad",
            ),
        ),
    ]
