# Generated by Django 4.2 on 2023-05-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ElectroStockApp", "0008_alter_element_initialstock_and_more")]

    operations = [
        migrations.RemoveField(model_name="box", name="element"),
        migrations.RemoveField(model_name="category", name="name"),
        migrations.RemoveField(model_name="element", name="category"),
        migrations.RemoveField(model_name="element", name="initialStock"),
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("Electromecanica", "Electromecanica"),
                    ("Electronica", "Electronica"),
                    ("Programacion", "Programacion"),
                    ("Otro", "Otro"),
                ],
                default="Electronica",
                max_length=30,
                verbose_name="Especialidad",
            ),
        ),
    ]
