# Generated by Django 4.2 on 2023-05-30 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ElectroStockApp", "0009_remove_box_element_remove_category_name_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ElectroStockApp.category",
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="initialStock",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_categories",
                to="ElectroStockApp.category",
            ),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("Electronica", "Electronica"),
                    ("Programacion", "Programacion"),
                    ("Otro", "Otro"),
                    ("Electromecanica", "Electromecanica"),
                ],
                default="Electronica",
                max_length=30,
                verbose_name="Especialidad",
            ),
        ),
    ]
