# Generated by Django 4.2 on 2023-05-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ElectroStockApp", "0011_box_element_alter_laboratory_specialty")]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("Electromecanica", "Electromecanica"),
                    ("Otro", "Otro"),
                    ("Programacion", "Programacion"),
                    ("Electronica", "Electronica"),
                ],
                default="Electronica",
                max_length=30,
                verbose_name="Especialidad",
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="initialStock",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("Electromecanica", "Electromecanica"),
                    ("Otro", "Otro"),
                    ("Programacion", "Programacion"),
                    ("Electronica", "Electronica"),
                ],
                default="Electronica",
                max_length=30,
                verbose_name="Especialidad",
            ),
        ),
    ]
