# Generated by Django 4.2 on 2023-05-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ElectroStockApp",
            "0012_customuser_specialty_alter_element_initialstock_and_more",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="specialty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Programacion", "Programacion"),
                    ("Electronica", "Electronica"),
                    ("Otro", "Otro"),
                    ("Electromecanica", "Electromecanica"),
                ],
                default="Electronica",
                max_length=30,
                null=True,
                verbose_name="Especialidad",
            ),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("Programacion", "Programacion"),
                    ("Electronica", "Electronica"),
                    ("Otro", "Otro"),
                    ("Electromecanica", "Electromecanica"),
                ],
                default="Electronica",
                max_length=30,
                verbose_name="Especialidad",
            ),
        ),
    ]
