# Generated by Django 4.2 on 2023-05-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ElectroStockApp", "0013_category_name_alter_customuser_specialty_and_more")
    ]

    operations = [
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Speciality", models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name="box", options={"verbose_name": "Box", "verbose_name_plural": "Boxes"}
        ),
        migrations.RenameField(
            model_name="course", old_name="number", new_name="grade"
        ),
        migrations.RemoveField(model_name="customuser", name="specialty"),
        migrations.AlterField(
            model_name="laboratory",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("Electromecanica", "Electromecanica"),
                    ("Otro", "Otro"),
                    ("Programacion", "Programacion"),
                    ("Electronica", "Electronica"),
                ],
                default="Electronica",
                max_length=30,
                verbose_name="Especialidad",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="specialties",
            field=models.ManyToManyField(to="ElectroStockApp.speciality"),
        ),
    ]
