# Generated by Django 4.2 on 2023-06-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ElectroStockApp", "0013_category_name_alter_customuser_specialty_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="box",
            options={"verbose_name": "Box", "verbose_name_plural": "Boxes"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="specialty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Electronica", "Electronica"),
                    ("Electromecanica", "Electromecanica"),
                    ("Programacion", "Programacion"),
                    ("Otro", "Otro"),
                ],
                default="Electronica",
                max_length=30,
                null=True,
                verbose_name="Especialidad",
            ),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("Electronica", "Electronica"),
                    ("Electromecanica", "Electromecanica"),
                    ("Programacion", "Programacion"),
                    ("Otro", "Otro"),
                ],
                default="Electronica",
                max_length=30,
                verbose_name="Especialidad",
            ),
        ),
    ]
