# Generated by Django 4.2 on 2023-05-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ElectroStockApp", "0014_speciality_alter_box_options_and_more")]

    operations = [
        migrations.AlterModelOptions(
            name="speciality",
            options={
                "verbose_name": "Especialidad",
                "verbose_name_plural": "Especialidades",
            },
        ),
        migrations.RemoveField(model_name="element", name="initialStock"),
        migrations.RemoveField(model_name="laboratory", name="specialty"),
        migrations.AddField(
            model_name="laboratory",
            name="specialties",
            field=models.ManyToManyField(
                blank=True, null=True, to="ElectroStockApp.speciality"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="specialties",
            field=models.ManyToManyField(
                blank=True, null=True, to="ElectroStockApp.speciality"
            ),
        ),
    ]
