# Generated by Django 4.2 on 2023-06-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectroStockApp', '0015_alter_customuser_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(blank=True, choices=[('Electromecanica', 'Electromecanica'), ('Electronica', 'Electronica'), ('Programacion', 'Programacion'), ('Otro', 'Otro')], default='Electronica', max_length=30, null=True, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='specialty',
            field=models.CharField(choices=[('Electromecanica', 'Electromecanica'), ('Electronica', 'Electronica'), ('Programacion', 'Programacion'), ('Otro', 'Otro')], default='Electronica', max_length=30, verbose_name='Especialidad'),
        ),
    ]
