# Generated by Django 4.2 on 2023-06-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ElectroStockApp", "0017_box_icon_alter_element_price_usd")]

    operations = [migrations.RemoveField(model_name="box", name="icon")]
